export const readingTexts={
leicht:[
{
minAge:5,
maxAge:8,
title:"Sofia und der Tag im See",
text:"An einem sonnigen Morgen freute sich Sofia auf einen besonderen Tag. Gemeinsam mit Freunden ging Sofia in den See. Dort hörten die Kinder fröhliche Geräusche und entdeckten viele spannende Dinge. Sie lachten zusammen, spielten und halfen sich gegenseitig. Nach einer Weile fand Sofia einen kleinen Korb. In dem Korb lag etwas Besonderes: viele bunte ___ . Alle Kinder freuten sich und wollten später gemeinsam damit spielen.",
question:"Welches Wort passt am besten in die Lücke?",
answers:["Steine","Fenster","Sterne"],
correctAnswer:"Sterne",
},
{
minAge:5,
maxAge:8,
title:"Ben und der Tag im Schulgarten",
text:"An einem sonnigen Morgen freute sich Ben auf einen besonderen Tag. Gemeinsam mit Freunden ging Ben in den Schulgarten. Dort hörten die Kinder fröhliche Geräusche und entdeckten viele spannende Dinge. Sie lachten zusammen, spielten und halfen sich gegenseitig. Nach einer Weile fand Ben einen kleinen Korb. In dem Korb lag etwas Besonderes: viele bunte ___ . Alle Kinder freuten sich und wollten später gemeinsam damit spielen.",
question:"Welches Wort passt am besten in die Lücke?",
answers:["Steine","Buntstifte","Fenster"],
correctAnswer:"Buntstifte",
},
{
minAge:5,
maxAge:8,
title:"Emma und der Tag im Ponyhof",
text:"An einem sonnigen Morgen freute sich Emma auf einen besonderen Tag. Gemeinsam mit Freunden ging Emma in den Ponyhof. Dort hörten die Kinder fröhliche Geräusche und entdeckten viele spannende Dinge. Sie lachten zusammen, spielten und halfen sich gegenseitig. Nach einer Weile fand Emma einen kleinen Korb. In dem Korb lag etwas Besonderes: viele bunte ___ . Alle Kinder freuten sich und wollten später gemeinsam damit spielen.",
question:"Welches Wort passt am besten in die Lücke?",
answers:["Fenster","Steine","Äpfel"],
correctAnswer:"Äpfel",
},
{
minAge:5,
maxAge:8,
title:"Mila und der Tag im Abenteuerinsel",
text:"An einem sonnigen Morgen freute sich Mila auf einen besonderen Tag. Gemeinsam mit Freunden ging Mila in den Abenteuerinsel. Dort hörten die Kinder fröhliche Geräusche und entdeckten viele spannende Dinge. Sie lachten zusammen, spielten und halfen sich gegenseitig. Nach einer Weile fand Mila einen kleinen Korb. In dem Korb lag etwas Besonderes: viele bunte ___ . Alle Kinder freuten sich und wollten später gemeinsam damit spielen.",
question:"Welches Wort passt am besten in die Lücke?",
answers:["Fenster","Steine","Kekse"],
correctAnswer:"Kekse",
},
{
minAge:5,
maxAge:8,
title:"Emma und der Tag im See",
text:"An einem sonnigen Morgen freute sich Emma auf einen besonderen Tag. Gemeinsam mit Freunden ging Emma in den See. Dort hörten die Kinder fröhliche Geräusche und entdeckten viele spannende Dinge. Sie lachten zusammen, spielten und halfen sich gegenseitig. Nach einer Weile fand Emma einen kleinen Korb. In dem Korb lag etwas Besonderes: viele bunte ___ . Alle Kinder freuten sich und wollten später gemeinsam damit spielen.",
question:"Welches Wort passt am besten in die Lücke?",
answers:["Steine","Fenster","Ballons"],
correctAnswer:"Ballons",
},
{
minAge:5,
maxAge:8,
title:"Ali und der Tag im Schulgarten",
text:"An einem sonnigen Morgen freute sich Ali auf einen besonderen Tag. Gemeinsam mit Freunden ging Ali in den Schulgarten. Dort hörten die Kinder fröhliche Geräusche und entdeckten viele spannende Dinge. Sie lachten zusammen, spielten und halfen sich gegenseitig. Nach einer Weile fand Ali einen kleinen Korb. In dem Korb lag etwas Besonderes: viele bunte ___ . Alle Kinder freuten sich und wollten später gemeinsam damit spielen.",
question:"Welches Wort passt am besten in die Lücke?",
answers:["Fenster","Äpfel","Steine"],
correctAnswer:"Äpfel",
},
{
minAge:5,
maxAge:8,
title:"Noah und der Tag im Bauernhof",
text:"An einem sonnigen Morgen freute sich Noah auf einen besonderen Tag. Gemeinsam mit Freunden ging Noah in den Bauernhof. Dort hörten die Kinder fröhliche Geräusche und entdeckten viele spannende Dinge. Sie lachten zusammen, spielten und halfen sich gegenseitig. Nach einer Weile fand Noah einen kleinen Korb. In dem Korb lag etwas Besonderes: viele bunte ___ . Alle Kinder freuten sich und wollten später gemeinsam damit spielen.",
question:"Welches Wort passt am besten in die Lücke?",
answers:["Steine","Fenster","Blumen"],
correctAnswer:"Blumen",
},
{
minAge:5,
maxAge:8,
title:"Ali und der Tag im Abenteuerinsel",
text:"An einem sonnigen Morgen freute sich Ali auf einen besonderen Tag. Gemeinsam mit Freunden ging Ali in den Abenteuerinsel. Dort hörten die Kinder fröhliche Geräusche und entdeckten viele spannende Dinge. Sie lachten zusammen, spielten und halfen sich gegenseitig. Nach einer Weile fand Ali einen kleinen Korb. In dem Korb lag etwas Besonderes: viele bunte ___ . Alle Kinder freuten sich und wollten später gemeinsam damit spielen.",
question:"Welches Wort passt am besten in die Lücke?",
answers:["Steine","Schmetterling","Fenster"],
correctAnswer:"Schmetterling",
},
{
minAge:5,
maxAge:8,
title:"Ben und der Tag im Bauernhof",
text:"An einem sonnigen Morgen freute sich Ben auf einen besonderen Tag. Gemeinsam mit Freunden ging Ben in den Bauernhof. Dort hörten die Kinder fröhliche Geräusche und entdeckten viele spannende Dinge. Sie lachten zusammen, spielten und halfen sich gegenseitig. Nach einer Weile fand Ben einen kleinen Korb. In dem Korb lag etwas Besonderes: viele bunte ___ . Alle Kinder freuten sich und wollten später gemeinsam damit spielen.",
question:"Welches Wort passt am besten in die Lücke?",
answers:["Steine","Fenster","Ballons"],
correctAnswer:"Ballons",
},
{
minAge:5,
maxAge:8,
title:"Paul und der Tag im Abenteuerinsel",
text:"An einem sonnigen Morgen freute sich Paul auf einen besonderen Tag. Gemeinsam mit Freunden ging Paul in den Abenteuerinsel. Dort hörten die Kinder fröhliche Geräusche und entdeckten viele spannende Dinge. Sie lachten zusammen, spielten und halfen sich gegenseitig. Nach einer Weile fand Paul einen kleinen Korb. In dem Korb lag etwas Besonderes: viele bunte ___ . Alle Kinder freuten sich und wollten später gemeinsam damit spielen.",
question:"Welches Wort passt am besten in die Lücke?",
answers:["Steine","Blumen","Fenster"],
correctAnswer:"Blumen",
},
{
minAge:5,
maxAge:8,
title:"Sofia und der Tag im Abenteuerinsel",
text:"An einem sonnigen Morgen freute sich Sofia auf einen besonderen Tag. Gemeinsam mit Freunden ging Sofia in den Abenteuerinsel. Dort hörten die Kinder fröhliche Geräusche und entdeckten viele spannende Dinge. Sie lachten zusammen, spielten und halfen sich gegenseitig. Nach einer Weile fand Sofia einen kleinen Korb. In dem Korb lag etwas Besonderes: viele bunte ___ . Alle Kinder freuten sich und wollten später gemeinsam damit spielen.",
question:"Welches Wort passt am besten in die Lücke?",
answers:["Fenster","Steine","Äpfel"],
correctAnswer:"Äpfel",
},
{
minAge:5,
maxAge:8,
title:"Ali und der Tag im Zauberwald",
text:"An einem sonnigen Morgen freute sich Ali auf einen besonderen Tag. Gemeinsam mit Freunden ging Ali in den Zauberwald. Dort hörten die Kinder fröhliche Geräusche und entdeckten viele spannende Dinge. Sie lachten zusammen, spielten und halfen sich gegenseitig. Nach einer Weile fand Ali einen kleinen Korb. In dem Korb lag etwas Besonderes: viele bunte ___ . Alle Kinder freuten sich und wollten später gemeinsam damit spielen.",
question:"Welches Wort passt am besten in die Lücke?",
answers:["Steine","Muscheln","Fenster"],
correctAnswer:"Muscheln",
},
{
minAge:5,
maxAge:8,
title:"Noah und der Tag im Regenbogenschule",
text:"An einem sonnigen Morgen freute sich Noah auf einen besonderen Tag. Gemeinsam mit Freunden ging Noah in den Regenbogenschule. Dort hörten die Kinder fröhliche Geräusche und entdeckten viele spannende Dinge. Sie lachten zusammen, spielten und halfen sich gegenseitig. Nach einer Weile fand Noah einen kleinen Korb. In dem Korb lag etwas Besonderes: viele bunte ___ . Alle Kinder freuten sich und wollten später gemeinsam damit spielen.",
question:"Welches Wort passt am besten in die Lücke?",
answers:["Fenster","Buntstifte","Steine"],
correctAnswer:"Buntstifte",
},
{
minAge:5,
maxAge:8,
title:"Leo und der Tag im Zauberwald",
text:"An einem sonnigen Morgen freute sich Leo auf einen besonderen Tag. Gemeinsam mit Freunden ging Leo in den Zauberwald. Dort hörten die Kinder fröhliche Geräusche und entdeckten viele spannende Dinge. Sie lachten zusammen, spielten und halfen sich gegenseitig. Nach einer Weile fand Leo einen kleinen Korb. In dem Korb lag etwas Besonderes: viele bunte ___ . Alle Kinder freuten sich und wollten später gemeinsam damit spielen.",
question:"Welches Wort passt am besten in die Lücke?",
answers:["Fenster","Steine","Hund"],
correctAnswer:"Hund",
},
{
minAge:5,
maxAge:8,
title:"Mila und der Tag im See",
text:"An einem sonnigen Morgen freute sich Mila auf einen besonderen Tag. Gemeinsam mit Freunden ging Mila in den See. Dort hörten die Kinder fröhliche Geräusche und entdeckten viele spannende Dinge. Sie lachten zusammen, spielten und halfen sich gegenseitig. Nach einer Weile fand Mila einen kleinen Korb. In dem Korb lag etwas Besonderes: viele bunte ___ . Alle Kinder freuten sich und wollten später gemeinsam damit spielen.",
question:"Welches Wort passt am besten in die Lücke?",
answers:["Fenster","Steine","Muscheln"],
correctAnswer:"Muscheln",
},
{
minAge:5,
maxAge:8,
title:"Ali und der Tag im Regenbogenschule",
text:"An einem sonnigen Morgen freute sich Ali auf einen besonderen Tag. Gemeinsam mit Freunden ging Ali in den Regenbogenschule. Dort hörten die Kinder fröhliche Geräusche und entdeckten viele spannende Dinge. Sie lachten zusammen, spielten und halfen sich gegenseitig. Nach einer Weile fand Ali einen kleinen Korb. In dem Korb lag etwas Besonderes: viele bunte ___ . Alle Kinder freuten sich und wollten später gemeinsam damit spielen.",
question:"Welches Wort passt am besten in die Lücke?",
answers:["Fenster","Steine","Buntstifte"],
correctAnswer:"Buntstifte",
},
{
minAge:5,
maxAge:8,
title:"Ben und der Tag im Spielplatz",
text:"An einem sonnigen Morgen freute sich Ben auf einen besonderen Tag. Gemeinsam mit Freunden ging Ben in den Spielplatz. Dort hörten die Kinder fröhliche Geräusche und entdeckten viele spannende Dinge. Sie lachten zusammen, spielten und halfen sich gegenseitig. Nach einer Weile fand Ben einen kleinen Korb. In dem Korb lag etwas Besonderes: viele bunte ___ . Alle Kinder freuten sich und wollten später gemeinsam damit spielen.",
question:"Welches Wort passt am besten in die Lücke?",
answers:["Steine","Pferd","Fenster"],
correctAnswer:"Pferd",
},
{
minAge:5,
maxAge:8,
title:"Mila und der Tag im Abenteuerinsel",
text:"An einem sonnigen Morgen freute sich Mila auf einen besonderen Tag. Gemeinsam mit Freunden ging Mila in den Abenteuerinsel. Dort hörten die Kinder fröhliche Geräusche und entdeckten viele spannende Dinge. Sie lachten zusammen, spielten und halfen sich gegenseitig. Nach einer Weile fand Mila einen kleinen Korb. In dem Korb lag etwas Besonderes: viele bunte ___ . Alle Kinder freuten sich und wollten später gemeinsam damit spielen.",
question:"Welches Wort passt am besten in die Lücke?",
answers:["Fenster","Ballons","Steine"],
correctAnswer:"Ballons",
},
{
minAge:5,
maxAge:8,
title:"Mila und der Tag im Abenteuerinsel",
text:"An einem sonnigen Morgen freute sich Mila auf einen besonderen Tag. Gemeinsam mit Freunden ging Mila in den Abenteuerinsel. Dort hörten die Kinder fröhliche Geräusche und entdeckten viele spannende Dinge. Sie lachten zusammen, spielten und halfen sich gegenseitig. Nach einer Weile fand Mila einen kleinen Korb. In dem Korb lag etwas Besonderes: viele bunte ___ . Alle Kinder freuten sich und wollten später gemeinsam damit spielen.",
question:"Welches Wort passt am besten in die Lücke?",
answers:["Steine","Fenster","Kekse"],
correctAnswer:"Kekse",
},
{
minAge:5,
maxAge:8,
title:"Noah und der Tag im Tierpark",
text:"An einem sonnigen Morgen freute sich Noah auf einen besonderen Tag. Gemeinsam mit Freunden ging Noah in den Tierpark. Dort hörten die Kinder fröhliche Geräusche und entdeckten viele spannende Dinge. Sie lachten zusammen, spielten und halfen sich gegenseitig. Nach einer Weile fand Noah einen kleinen Korb. In dem Korb lag etwas Besonderes: viele bunte ___ . Alle Kinder freuten sich und wollten später gemeinsam damit spielen.",
question:"Welches Wort passt am besten in die Lücke?",
answers:["Fenster","Steine","Buntstifte"],
correctAnswer:"Buntstifte",
},
{
minAge:5,
maxAge:8,
title:"Mia und der Tag im Tierpark",
text:"An einem sonnigen Morgen freute sich Mia auf einen besonderen Tag. Gemeinsam mit Freunden ging Mia in den Tierpark. Dort hörten die Kinder fröhliche Geräusche und entdeckten viele spannende Dinge. Sie lachten zusammen, spielten und halfen sich gegenseitig. Nach einer Weile fand Mia einen kleinen Korb. In dem Korb lag etwas Besonderes: viele bunte ___ . Alle Kinder freuten sich und wollten später gemeinsam damit spielen.",
question:"Welches Wort passt am besten in die Lücke?",
answers:["Fenster","Steine","Kekse"],
correctAnswer:"Kekse",
},
{
minAge:5,
maxAge:8,
title:"Noah und der Tag im Tierpark",
text:"An einem sonnigen Morgen freute sich Noah auf einen besonderen Tag. Gemeinsam mit Freunden ging Noah in den Tierpark. Dort hörten die Kinder fröhliche Geräusche und entdeckten viele spannende Dinge. Sie lachten zusammen, spielten und halfen sich gegenseitig. Nach einer Weile fand Noah einen kleinen Korb. In dem Korb lag etwas Besonderes: viele bunte ___ . Alle Kinder freuten sich und wollten später gemeinsam damit spielen.",
question:"Welches Wort passt am besten in die Lücke?",
answers:["Steine","Fenster","Kekse"],
correctAnswer:"Kekse",
},
{
minAge:5,
maxAge:8,
title:"Mila und der Tag im Zauberwald",
text:"An einem sonnigen Morgen freute sich Mila auf einen besonderen Tag. Gemeinsam mit Freunden ging Mila in den Zauberwald. Dort hörten die Kinder fröhliche Geräusche und entdeckten viele spannende Dinge. Sie lachten zusammen, spielten und halfen sich gegenseitig. Nach einer Weile fand Mila einen kleinen Korb. In dem Korb lag etwas Besonderes: viele bunte ___ . Alle Kinder freuten sich und wollten später gemeinsam damit spielen.",
question:"Welches Wort passt am besten in die Lücke?",
answers:["Sterne","Steine","Fenster"],
correctAnswer:"Sterne",
},
{
minAge:5,
maxAge:8,
title:"Paul und der Tag im Regenbogenschule",
text:"An einem sonnigen Morgen freute sich Paul auf einen besonderen Tag. Gemeinsam mit Freunden ging Paul in den Regenbogenschule. Dort hörten die Kinder fröhliche Geräusche und entdeckten viele spannende Dinge. Sie lachten zusammen, spielten und halfen sich gegenseitig. Nach einer Weile fand Paul einen kleinen Korb. In dem Korb lag etwas Besonderes: viele bunte ___ . Alle Kinder freuten sich und wollten später gemeinsam damit spielen.",
question:"Welches Wort passt am besten in die Lücke?",
answers:["Muscheln","Fenster","Steine"],
correctAnswer:"Muscheln",
},
{
minAge:5,
maxAge:8,
title:"Paul und der Tag im Tierpark",
text:"An einem sonnigen Morgen freute sich Paul auf einen besonderen Tag. Gemeinsam mit Freunden ging Paul in den Tierpark. Dort hörten die Kinder fröhliche Geräusche und entdeckten viele spannende Dinge. Sie lachten zusammen, spielten und halfen sich gegenseitig. Nach einer Weile fand Paul einen kleinen Korb. In dem Korb lag etwas Besonderes: viele bunte ___ . Alle Kinder freuten sich und wollten später gemeinsam damit spielen.",
question:"Welches Wort passt am besten in die Lücke?",
answers:["Buntstifte","Steine","Fenster"],
correctAnswer:"Buntstifte",
},
{
minAge:5,
maxAge:8,
title:"Sofia und der Tag im Ponyhof",
text:"An einem sonnigen Morgen freute sich Sofia auf einen besonderen Tag. Gemeinsam mit Freunden ging Sofia in den Ponyhof. Dort hörten die Kinder fröhliche Geräusche und entdeckten viele spannende Dinge. Sie lachten zusammen, spielten und halfen sich gegenseitig. Nach einer Weile fand Sofia einen kleinen Korb. In dem Korb lag etwas Besonderes: viele bunte ___ . Alle Kinder freuten sich und wollten später gemeinsam damit spielen.",
question:"Welches Wort passt am besten in die Lücke?",
answers:["Pferd","Fenster","Steine"],
correctAnswer:"Pferd",
},
{
minAge:5,
maxAge:8,
title:"Noah und der Tag im Zauberwald",
text:"An einem sonnigen Morgen freute sich Noah auf einen besonderen Tag. Gemeinsam mit Freunden ging Noah in den Zauberwald. Dort hörten die Kinder fröhliche Geräusche und entdeckten viele spannende Dinge. Sie lachten zusammen, spielten und halfen sich gegenseitig. Nach einer Weile fand Noah einen kleinen Korb. In dem Korb lag etwas Besonderes: viele bunte ___ . Alle Kinder freuten sich und wollten später gemeinsam damit spielen.",
question:"Welches Wort passt am besten in die Lücke?",
answers:["Fenster","Schmetterling","Steine"],
correctAnswer:"Schmetterling",
},
{
minAge:5,
maxAge:8,
title:"Mila und der Tag im Zauberwald",
text:"An einem sonnigen Morgen freute sich Mila auf einen besonderen Tag. Gemeinsam mit Freunden ging Mila in den Zauberwald. Dort hörten die Kinder fröhliche Geräusche und entdeckten viele spannende Dinge. Sie lachten zusammen, spielten und halfen sich gegenseitig. Nach einer Weile fand Mila einen kleinen Korb. In dem Korb lag etwas Besonderes: viele bunte ___ . Alle Kinder freuten sich und wollten später gemeinsam damit spielen.",
question:"Welches Wort passt am besten in die Lücke?",
answers:["Steine","Fenster","Kekse"],
correctAnswer:"Kekse",
},
{
minAge:5,
maxAge:8,
title:"Ben und der Tag im Ponyhof",
text:"An einem sonnigen Morgen freute sich Ben auf einen besonderen Tag. Gemeinsam mit Freunden ging Ben in den Ponyhof. Dort hörten die Kinder fröhliche Geräusche und entdeckten viele spannende Dinge. Sie lachten zusammen, spielten und halfen sich gegenseitig. Nach einer Weile fand Ben einen kleinen Korb. In dem Korb lag etwas Besonderes: viele bunte ___ . Alle Kinder freuten sich und wollten später gemeinsam damit spielen.",
question:"Welches Wort passt am besten in die Lücke?",
answers:["Steine","Sterne","Fenster"],
correctAnswer:"Sterne",
},
{
minAge:5,
maxAge:8,
title:"Leo und der Tag im Spielplatz",
text:"An einem sonnigen Morgen freute sich Leo auf einen besonderen Tag. Gemeinsam mit Freunden ging Leo in den Spielplatz. Dort hörten die Kinder fröhliche Geräusche und entdeckten viele spannende Dinge. Sie lachten zusammen, spielten und halfen sich gegenseitig. Nach einer Weile fand Leo einen kleinen Korb. In dem Korb lag etwas Besonderes: viele bunte ___ . Alle Kinder freuten sich und wollten später gemeinsam damit spielen.",
question:"Welches Wort passt am besten in die Lücke?",
answers:["Blumen","Steine","Fenster"],
correctAnswer:"Blumen",
},
{
minAge:5,
maxAge:8,
title:"Sofia und der Tag im Abenteuerinsel",
text:"An einem sonnigen Morgen freute sich Sofia auf einen besonderen Tag. Gemeinsam mit Freunden ging Sofia in den Abenteuerinsel. Dort hörten die Kinder fröhliche Geräusche und entdeckten viele spannende Dinge. Sie lachten zusammen, spielten und halfen sich gegenseitig. Nach einer Weile fand Sofia einen kleinen Korb. In dem Korb lag etwas Besonderes: viele bunte ___ . Alle Kinder freuten sich und wollten später gemeinsam damit spielen.",
question:"Welches Wort passt am besten in die Lücke?",
answers:["Buntstifte","Steine","Fenster"],
correctAnswer:"Buntstifte",
},
{
minAge:5,
maxAge:8,
title:"Noah und der Tag im Märchenwald",
text:"An einem sonnigen Morgen freute sich Noah auf einen besonderen Tag. Gemeinsam mit Freunden ging Noah in den Märchenwald. Dort hörten die Kinder fröhliche Geräusche und entdeckten viele spannende Dinge. Sie lachten zusammen, spielten und halfen sich gegenseitig. Nach einer Weile fand Noah einen kleinen Korb. In dem Korb lag etwas Besonderes: viele bunte ___ . Alle Kinder freuten sich und wollten später gemeinsam damit spielen.",
question:"Welches Wort passt am besten in die Lücke?",
answers:["Fenster","Pferd","Steine"],
correctAnswer:"Pferd",
},
{
minAge:5,
maxAge:8,
title:"Ali und der Tag im See",
text:"An einem sonnigen Morgen freute sich Ali auf einen besonderen Tag. Gemeinsam mit Freunden ging Ali in den See. Dort hörten die Kinder fröhliche Geräusche und entdeckten viele spannende Dinge. Sie lachten zusammen, spielten und halfen sich gegenseitig. Nach einer Weile fand Ali einen kleinen Korb. In dem Korb lag etwas Besonderes: viele bunte ___ . Alle Kinder freuten sich und wollten später gemeinsam damit spielen.",
question:"Welches Wort passt am besten in die Lücke?",
answers:["Fenster","Steine","Ballons"],
correctAnswer:"Ballons",
},
{
minAge:5,
maxAge:8,
title:"Lina und der Tag im Abenteuerinsel",
text:"An einem sonnigen Morgen freute sich Lina auf einen besonderen Tag. Gemeinsam mit Freunden ging Lina in den Abenteuerinsel. Dort hörten die Kinder fröhliche Geräusche und entdeckten viele spannende Dinge. Sie lachten zusammen, spielten und halfen sich gegenseitig. Nach einer Weile fand Lina einen kleinen Korb. In dem Korb lag etwas Besonderes: viele bunte ___ . Alle Kinder freuten sich und wollten später gemeinsam damit spielen.",
question:"Welches Wort passt am besten in die Lücke?",
answers:["Äpfel","Fenster","Steine"],
correctAnswer:"Äpfel",
},
{
minAge:5,
maxAge:8,
title:"Sofia und der Tag im Märchenwald",
text:"An einem sonnigen Morgen freute sich Sofia auf einen besonderen Tag. Gemeinsam mit Freunden ging Sofia in den Märchenwald. Dort hörten die Kinder fröhliche Geräusche und entdeckten viele spannende Dinge. Sie lachten zusammen, spielten und halfen sich gegenseitig. Nach einer Weile fand Sofia einen kleinen Korb. In dem Korb lag etwas Besonderes: viele bunte ___ . Alle Kinder freuten sich und wollten später gemeinsam damit spielen.",
question:"Welches Wort passt am besten in die Lücke?",
answers:["Äpfel","Steine","Fenster"],
correctAnswer:"Äpfel",
},
{
minAge:5,
maxAge:8,
title:"Ben und der Tag im Schulgarten",
text:"An einem sonnigen Morgen freute sich Ben auf einen besonderen Tag. Gemeinsam mit Freunden ging Ben in den Schulgarten. Dort hörten die Kinder fröhliche Geräusche und entdeckten viele spannende Dinge. Sie lachten zusammen, spielten und halfen sich gegenseitig. Nach einer Weile fand Ben einen kleinen Korb. In dem Korb lag etwas Besonderes: viele bunte ___ . Alle Kinder freuten sich und wollten später gemeinsam damit spielen.",
question:"Welches Wort passt am besten in die Lücke?",
answers:["Steine","Fenster","Blumen"],
correctAnswer:"Blumen",
},
{
minAge:5,
maxAge:8,
title:"Lina und der Tag im Zauberwald",
text:"An einem sonnigen Morgen freute sich Lina auf einen besonderen Tag. Gemeinsam mit Freunden ging Lina in den Zauberwald. Dort hörten die Kinder fröhliche Geräusche und entdeckten viele spannende Dinge. Sie lachten zusammen, spielten und halfen sich gegenseitig. Nach einer Weile fand Lina einen kleinen Korb. In dem Korb lag etwas Besonderes: viele bunte ___ . Alle Kinder freuten sich und wollten später gemeinsam damit spielen.",
question:"Welches Wort passt am besten in die Lücke?",
answers:["Steine","Sterne","Fenster"],
correctAnswer:"Sterne",
},
{
minAge:5,
maxAge:8,
title:"Ali und der Tag im Zauberwald",
text:"An einem sonnigen Morgen freute sich Ali auf einen besonderen Tag. Gemeinsam mit Freunden ging Ali in den Zauberwald. Dort hörten die Kinder fröhliche Geräusche und entdeckten viele spannende Dinge. Sie lachten zusammen, spielten und halfen sich gegenseitig. Nach einer Weile fand Ali einen kleinen Korb. In dem Korb lag etwas Besonderes: viele bunte ___ . Alle Kinder freuten sich und wollten später gemeinsam damit spielen.",
question:"Welches Wort passt am besten in die Lücke?",
answers:["Steine","Fenster","Schmetterling"],
correctAnswer:"Schmetterling",
},
{
minAge:5,
maxAge:8,
title:"Sofia und der Tag im Spielplatz",
text:"An einem sonnigen Morgen freute sich Sofia auf einen besonderen Tag. Gemeinsam mit Freunden ging Sofia in den Spielplatz. Dort hörten die Kinder fröhliche Geräusche und entdeckten viele spannende Dinge. Sie lachten zusammen, spielten und halfen sich gegenseitig. Nach einer Weile fand Sofia einen kleinen Korb. In dem Korb lag etwas Besonderes: viele bunte ___ . Alle Kinder freuten sich und wollten später gemeinsam damit spielen.",
question:"Welches Wort passt am besten in die Lücke?",
answers:["Fenster","Steine","Ballons"],
correctAnswer:"Ballons",
},
{
minAge:5,
maxAge:8,
title:"Ben und der Tag im Schulgarten",
text:"An einem sonnigen Morgen freute sich Ben auf einen besonderen Tag. Gemeinsam mit Freunden ging Ben in den Schulgarten. Dort hörten die Kinder fröhliche Geräusche und entdeckten viele spannende Dinge. Sie lachten zusammen, spielten und halfen sich gegenseitig. Nach einer Weile fand Ben einen kleinen Korb. In dem Korb lag etwas Besonderes: viele bunte ___ . Alle Kinder freuten sich und wollten später gemeinsam damit spielen.",
question:"Welches Wort passt am besten in die Lücke?",
answers:["Blumen","Fenster","Steine"],
correctAnswer:"Blumen",
},
{
minAge:5,
maxAge:8,
title:"Paul und der Tag im Zauberwald",
text:"An einem sonnigen Morgen freute sich Paul auf einen besonderen Tag. Gemeinsam mit Freunden ging Paul in den Zauberwald. Dort hörten die Kinder fröhliche Geräusche und entdeckten viele spannende Dinge. Sie lachten zusammen, spielten und halfen sich gegenseitig. Nach einer Weile fand Paul einen kleinen Korb. In dem Korb lag etwas Besonderes: viele bunte ___ . Alle Kinder freuten sich und wollten später gemeinsam damit spielen.",
question:"Welches Wort passt am besten in die Lücke?",
answers:["Fenster","Hund","Steine"],
correctAnswer:"Hund",
},
{
minAge:5,
maxAge:8,
title:"Mia und der Tag im Märchenwald",
text:"An einem sonnigen Morgen freute sich Mia auf einen besonderen Tag. Gemeinsam mit Freunden ging Mia in den Märchenwald. Dort hörten die Kinder fröhliche Geräusche und entdeckten viele spannende Dinge. Sie lachten zusammen, spielten und halfen sich gegenseitig. Nach einer Weile fand Mia einen kleinen Korb. In dem Korb lag etwas Besonderes: viele bunte ___ . Alle Kinder freuten sich und wollten später gemeinsam damit spielen.",
question:"Welches Wort passt am besten in die Lücke?",
answers:["Fenster","Steine","Äpfel"],
correctAnswer:"Äpfel",
},
{
minAge:5,
maxAge:8,
title:"Mila und der Tag im Tierpark",
text:"An einem sonnigen Morgen freute sich Mila auf einen besonderen Tag. Gemeinsam mit Freunden ging Mila in den Tierpark. Dort hörten die Kinder fröhliche Geräusche und entdeckten viele spannende Dinge. Sie lachten zusammen, spielten und halfen sich gegenseitig. Nach einer Weile fand Mila einen kleinen Korb. In dem Korb lag etwas Besonderes: viele bunte ___ . Alle Kinder freuten sich und wollten später gemeinsam damit spielen.",
question:"Welches Wort passt am besten in die Lücke?",
answers:["Fenster","Hund","Steine"],
correctAnswer:"Hund",
},
{
minAge:5,
maxAge:8,
title:"Mila und der Tag im Schulgarten",
text:"An einem sonnigen Morgen freute sich Mila auf einen besonderen Tag. Gemeinsam mit Freunden ging Mila in den Schulgarten. Dort hörten die Kinder fröhliche Geräusche und entdeckten viele spannende Dinge. Sie lachten zusammen, spielten und halfen sich gegenseitig. Nach einer Weile fand Mila einen kleinen Korb. In dem Korb lag etwas Besonderes: viele bunte ___ . Alle Kinder freuten sich und wollten später gemeinsam damit spielen.",
question:"Welches Wort passt am besten in die Lücke?",
answers:["Fenster","Schmetterling","Steine"],
correctAnswer:"Schmetterling",
},
{
minAge:5,
maxAge:8,
title:"Ali und der Tag im Tierpark",
text:"An einem sonnigen Morgen freute sich Ali auf einen besonderen Tag. Gemeinsam mit Freunden ging Ali in den Tierpark. Dort hörten die Kinder fröhliche Geräusche und entdeckten viele spannende Dinge. Sie lachten zusammen, spielten und halfen sich gegenseitig. Nach einer Weile fand Ali einen kleinen Korb. In dem Korb lag etwas Besonderes: viele bunte ___ . Alle Kinder freuten sich und wollten später gemeinsam damit spielen.",
question:"Welches Wort passt am besten in die Lücke?",
answers:["Fenster","Steine","Blumen"],
correctAnswer:"Blumen",
},
{
minAge:5,
maxAge:8,
title:"Ali und der Tag im Tierpark",
text:"An einem sonnigen Morgen freute sich Ali auf einen besonderen Tag. Gemeinsam mit Freunden ging Ali in den Tierpark. Dort hörten die Kinder fröhliche Geräusche und entdeckten viele spannende Dinge. Sie lachten zusammen, spielten und halfen sich gegenseitig. Nach einer Weile fand Ali einen kleinen Korb. In dem Korb lag etwas Besonderes: viele bunte ___ . Alle Kinder freuten sich und wollten später gemeinsam damit spielen.",
question:"Welches Wort passt am besten in die Lücke?",
answers:["Kekse","Steine","Fenster"],
correctAnswer:"Kekse",
},
{
minAge:5,
maxAge:8,
title:"Noah und der Tag im Ponyhof",
text:"An einem sonnigen Morgen freute sich Noah auf einen besonderen Tag. Gemeinsam mit Freunden ging Noah in den Ponyhof. Dort hörten die Kinder fröhliche Geräusche und entdeckten viele spannende Dinge. Sie lachten zusammen, spielten und halfen sich gegenseitig. Nach einer Weile fand Noah einen kleinen Korb. In dem Korb lag etwas Besonderes: viele bunte ___ . Alle Kinder freuten sich und wollten später gemeinsam damit spielen.",
question:"Welches Wort passt am besten in die Lücke?",
answers:["Schmetterling","Steine","Fenster"],
correctAnswer:"Schmetterling",
},
{
minAge:5,
maxAge:8,
title:"Lina und der Tag im Abenteuerinsel",
text:"An einem sonnigen Morgen freute sich Lina auf einen besonderen Tag. Gemeinsam mit Freunden ging Lina in den Abenteuerinsel. Dort hörten die Kinder fröhliche Geräusche und entdeckten viele spannende Dinge. Sie lachten zusammen, spielten und halfen sich gegenseitig. Nach einer Weile fand Lina einen kleinen Korb. In dem Korb lag etwas Besonderes: viele bunte ___ . Alle Kinder freuten sich und wollten später gemeinsam damit spielen.",
question:"Welches Wort passt am besten in die Lücke?",
answers:["Fenster","Steine","Sterne"],
correctAnswer:"Sterne",
},
{
minAge:5,
maxAge:8,
title:"Paul und der Tag im Märchenwald",
text:"An einem sonnigen Morgen freute sich Paul auf einen besonderen Tag. Gemeinsam mit Freunden ging Paul in den Märchenwald. Dort hörten die Kinder fröhliche Geräusche und entdeckten viele spannende Dinge. Sie lachten zusammen, spielten und halfen sich gegenseitig. Nach einer Weile fand Paul einen kleinen Korb. In dem Korb lag etwas Besonderes: viele bunte ___ . Alle Kinder freuten sich und wollten später gemeinsam damit spielen.",
question:"Welches Wort passt am besten in die Lücke?",
answers:["Fenster","Schmetterling","Steine"],
correctAnswer:"Schmetterling",
},
{
minAge:5,
maxAge:8,
title:"Leo und der Tag im Tierpark",
text:"An einem sonnigen Morgen freute sich Leo auf einen besonderen Tag. Gemeinsam mit Freunden ging Leo in den Tierpark. Dort hörten die Kinder fröhliche Geräusche und entdeckten viele spannende Dinge. Sie lachten zusammen, spielten und halfen sich gegenseitig. Nach einer Weile fand Leo einen kleinen Korb. In dem Korb lag etwas Besonderes: viele bunte ___ . Alle Kinder freuten sich und wollten später gemeinsam damit spielen.",
question:"Welches Wort passt am besten in die Lücke?",
answers:["Sterne","Steine","Fenster"],
correctAnswer:"Sterne",
},
]
};