export const readingTexts={
leicht:[
{
minAge:5,maxAge:7,
title:"Ben's Happy Adventure",
text:"Ben had a happy day today. In the morning, Ben went to the zoo with friends. They laughed, played games, and saw many interesting things. Near a tree, Ben saw a friendly cat. The little cat looked hungry, so Ben shared some cupcakes. Everyone smiled and had fun together. At the end of the day, Ben felt happy because sharing and helping friends is important.",
question:"What animal did Ben see?",
answers:["Cat","Lion","Elephant"],
correctAnswer:"Cat",
},
{
minAge:5,maxAge:7,
title:"Ben and the Little Cat",
text:"Ben had a happy day today. In the morning, Ben went to the school garden with friends. They laughed, played games, and saw many interesting things. Near a tree, Ben saw a friendly cat. The little cat looked hungry, so Ben shared some bananas. Everyone smiled and had fun together. At the end of the day, Ben felt happy because sharing and helping friends is important.",
question:"What animal did Ben see?",
answers:["Cat","Lion","Elephant"],
correctAnswer:"Cat",
},
{
minAge:5,maxAge:7,
title:"Leo and the Magic Day",
text:"Leo had a happy day today. In the morning, Leo went to the school garden with friends. They laughed, played games, and saw many interesting things. Near a tree, Leo saw a friendly horse. The little horse looked hungry, so Leo shared some carrots. Everyone smiled and had fun together. At the end of the day, Leo felt happy because sharing and helping friends is important.",
question:"What animal did Leo see?",
answers:["Horse","Lion","Elephant"],
correctAnswer:"Horse",
},
{
minAge:5,maxAge:7,
title:"Sofia's Happy Adventure",
text:"Sofia had a happy day today. In the morning, Sofia went to the playground with friends. They laughed, played games, and saw many interesting things. Near a tree, Sofia saw a friendly bird. The little bird looked hungry, so Sofia shared some carrots. Everyone smiled and had fun together. At the end of the day, Sofia felt happy because sharing and helping friends is important.",
question:"What animal did Sofia see?",
answers:["Bird","Lion","Elephant"],
correctAnswer:"Bird",
},
{
minAge:5,maxAge:7,
title:"Sofia's Happy Adventure",
text:"Sofia had a happy day today. In the morning, Sofia went to the lake with friends. They laughed, played games, and saw many interesting things. Near a tree, Sofia saw a friendly horse. The little horse looked hungry, so Sofia shared some apples. Everyone smiled and had fun together. At the end of the day, Sofia felt happy because sharing and helping friends is important.",
question:"What animal did Sofia see?",
answers:["Horse","Lion","Elephant"],
correctAnswer:"Horse",
},
{
minAge:5,maxAge:7,
title:"Emma and the Little Bird",
text:"Emma had a happy day today. In the morning, Emma went to the zoo with friends. They laughed, played games, and saw many interesting things. Near a tree, Emma saw a friendly bird. The little bird looked hungry, so Emma shared some cupcakes. Everyone smiled and had fun together. At the end of the day, Emma felt happy because sharing and helping friends is important.",
question:"What animal did Emma see?",
answers:["Bird","Lion","Elephant"],
correctAnswer:"Bird",
},
{
minAge:5,maxAge:7,
title:"The Friendly Cat",
text:"Max had a happy day today. In the morning, Max went to the playground with friends. They laughed, played games, and saw many interesting things. Near a tree, Max saw a friendly cat. The little cat looked hungry, so Max shared some apples. Everyone smiled and had fun together. At the end of the day, Max felt happy because sharing and helping friends is important.",
question:"What animal did Max see?",
answers:["Cat","Lion","Elephant"],
correctAnswer:"Cat",
},
{
minAge:5,maxAge:7,
title:"The Friendly Bird",
text:"Noah had a happy day today. In the morning, Noah went to the park with friends. They laughed, played games, and saw many interesting things. Near a tree, Noah saw a friendly bird. The little bird looked hungry, so Noah shared some cupcakes. Everyone smiled and had fun together. At the end of the day, Noah felt happy because sharing and helping friends is important.",
question:"What animal did Noah see?",
answers:["Bird","Lion","Elephant"],
correctAnswer:"Bird",
},
{
minAge:5,maxAge:7,
title:"The Day at the Zoo",
text:"Noah had a happy day today. In the morning, Noah went to the zoo with friends. They laughed, played games, and saw many interesting things. Near a tree, Noah saw a friendly cat. The little cat looked hungry, so Noah shared some carrots. Everyone smiled and had fun together. At the end of the day, Noah felt happy because sharing and helping friends is important.",
question:"What animal did Noah see?",
answers:["Cat","Lion","Elephant"],
correctAnswer:"Cat",
},
{
minAge:5,maxAge:7,
title:"The Friendly Dog",
text:"Lily had a happy day today. In the morning, Lily went to the farm with friends. They laughed, played games, and saw many interesting things. Near a tree, Lily saw a friendly dog. The little dog looked hungry, so Lily shared some apples. Everyone smiled and had fun together. At the end of the day, Lily felt happy because sharing and helping friends is important.",
question:"What animal did Lily see?",
answers:["Dog","Lion","Elephant"],
correctAnswer:"Dog",
},
{
minAge:5,maxAge:7,
title:"The Day at the Farm",
text:"Lily had a happy day today. In the morning, Lily went to the farm with friends. They laughed, played games, and saw many interesting things. Near a tree, Lily saw a friendly rabbit. The little rabbit looked hungry, so Lily shared some sandwiches. Everyone smiled and had fun together. At the end of the day, Lily felt happy because sharing and helping friends is important.",
question:"What animal did Lily see?",
answers:["Rabbit","Lion","Elephant"],
correctAnswer:"Rabbit",
},
{
minAge:5,maxAge:7,
title:"The Day at the Playground",
text:"Noah had a happy day today. In the morning, Noah went to the playground with friends. They laughed, played games, and saw many interesting things. Near a tree, Noah saw a friendly cat. The little cat looked hungry, so Noah shared some cookies. Everyone smiled and had fun together. At the end of the day, Noah felt happy because sharing and helping friends is important.",
question:"What animal did Noah see?",
answers:["Cat","Lion","Elephant"],
correctAnswer:"Cat",
},
{
minAge:5,maxAge:7,
title:"The Day at the Lake",
text:"Lily had a happy day today. In the morning, Lily went to the lake with friends. They laughed, played games, and saw many interesting things. Near a tree, Lily saw a friendly cat. The little cat looked hungry, so Lily shared some carrots. Everyone smiled and had fun together. At the end of the day, Lily felt happy because sharing and helping friends is important.",
question:"What animal did Lily see?",
answers:["Cat","Lion","Elephant"],
correctAnswer:"Cat",
},
{
minAge:5,maxAge:7,
title:"The Friendly Cat",
text:"Lily had a happy day today. In the morning, Lily went to the school garden with friends. They laughed, played games, and saw many interesting things. Near a tree, Lily saw a friendly cat. The little cat looked hungry, so Lily shared some cupcakes. Everyone smiled and had fun together. At the end of the day, Lily felt happy because sharing and helping friends is important.",
question:"What animal did Lily see?",
answers:["Cat","Lion","Elephant"],
correctAnswer:"Cat",
},
{
minAge:5,maxAge:7,
title:"Tom and the Little Bird",
text:"Tom had a happy day today. In the morning, Tom went to the lake with friends. They laughed, played games, and saw many interesting things. Near a tree, Tom saw a friendly bird. The little bird looked hungry, so Tom shared some cupcakes. Everyone smiled and had fun together. At the end of the day, Tom felt happy because sharing and helping friends is important.",
question:"What animal did Tom see?",
answers:["Bird","Lion","Elephant"],
correctAnswer:"Bird",
},
{
minAge:5,maxAge:7,
title:"Sofia and the Little Dog",
text:"Sofia had a happy day today. In the morning, Sofia went to the school garden with friends. They laughed, played games, and saw many interesting things. Near a tree, Sofia saw a friendly dog. The little dog looked hungry, so Sofia shared some bananas. Everyone smiled and had fun together. At the end of the day, Sofia felt happy because sharing and helping friends is important.",
question:"What animal did Sofia see?",
answers:["Dog","Lion","Elephant"],
correctAnswer:"Dog",
},
{
minAge:5,maxAge:7,
title:"The Day at the Farm",
text:"Lily had a happy day today. In the morning, Lily went to the farm with friends. They laughed, played games, and saw many interesting things. Near a tree, Lily saw a friendly rabbit. The little rabbit looked hungry, so Lily shared some bananas. Everyone smiled and had fun together. At the end of the day, Lily felt happy because sharing and helping friends is important.",
question:"What animal did Lily see?",
answers:["Rabbit","Lion","Elephant"],
correctAnswer:"Rabbit",
},
{
minAge:5,maxAge:7,
title:"The Friendly Duck",
text:"Ben had a happy day today. In the morning, Ben went to the lake with friends. They laughed, played games, and saw many interesting things. Near a tree, Ben saw a friendly duck. The little duck looked hungry, so Ben shared some carrots. Everyone smiled and had fun together. At the end of the day, Ben felt happy because sharing and helping friends is important.",
question:"What animal did Ben see?",
answers:["Duck","Lion","Elephant"],
correctAnswer:"Duck",
},
{
minAge:5,maxAge:7,
title:"Tom and the Magic Day",
text:"Tom had a happy day today. In the morning, Tom went to the park with friends. They laughed, played games, and saw many interesting things. Near a tree, Tom saw a friendly duck. The little duck looked hungry, so Tom shared some bananas. Everyone smiled and had fun together. At the end of the day, Tom felt happy because sharing and helping friends is important.",
question:"What animal did Tom see?",
answers:["Duck","Lion","Elephant"],
correctAnswer:"Duck",
},
{
minAge:5,maxAge:7,
title:"The Friendly Rabbit",
text:"Leo had a happy day today. In the morning, Leo went to the park with friends. They laughed, played games, and saw many interesting things. Near a tree, Leo saw a friendly rabbit. The little rabbit looked hungry, so Leo shared some cookies. Everyone smiled and had fun together. At the end of the day, Leo felt happy because sharing and helping friends is important.",
question:"What animal did Leo see?",
answers:["Rabbit","Lion","Elephant"],
correctAnswer:"Rabbit",
},
{
minAge:5,maxAge:7,
title:"The Day at the Playground",
text:"Mia had a happy day today. In the morning, Mia went to the playground with friends. They laughed, played games, and saw many interesting things. Near a tree, Mia saw a friendly duck. The little duck looked hungry, so Mia shared some sandwiches. Everyone smiled and had fun together. At the end of the day, Mia felt happy because sharing and helping friends is important.",
question:"What animal did Mia see?",
answers:["Duck","Lion","Elephant"],
correctAnswer:"Duck",
},
{
minAge:5,maxAge:7,
title:"Lily's Happy Adventure",
text:"Lily had a happy day today. In the morning, Lily went to the park with friends. They laughed, played games, and saw many interesting things. Near a tree, Lily saw a friendly cat. The little cat looked hungry, so Lily shared some cupcakes. Everyone smiled and had fun together. At the end of the day, Lily felt happy because sharing and helping friends is important.",
question:"What animal did Lily see?",
answers:["Cat","Lion","Elephant"],
correctAnswer:"Cat",
},
{
minAge:5,maxAge:7,
title:"Sofia and the Magic Day",
text:"Sofia had a happy day today. In the morning, Sofia went to the farm with friends. They laughed, played games, and saw many interesting things. Near a tree, Sofia saw a friendly horse. The little horse looked hungry, so Sofia shared some bananas. Everyone smiled and had fun together. At the end of the day, Sofia felt happy because sharing and helping friends is important.",
question:"What animal did Sofia see?",
answers:["Horse","Lion","Elephant"],
correctAnswer:"Horse",
},
{
minAge:5,maxAge:7,
title:"The Day at the Park",
text:"Emma had a happy day today. In the morning, Emma went to the park with friends. They laughed, played games, and saw many interesting things. Near a tree, Emma saw a friendly rabbit. The little rabbit looked hungry, so Emma shared some cupcakes. Everyone smiled and had fun together. At the end of the day, Emma felt happy because sharing and helping friends is important.",
question:"What animal did Emma see?",
answers:["Rabbit","Lion","Elephant"],
correctAnswer:"Rabbit",
},
{
minAge:5,maxAge:7,
title:"Tom's Happy Adventure",
text:"Tom had a happy day today. In the morning, Tom went to the farm with friends. They laughed, played games, and saw many interesting things. Near a tree, Tom saw a friendly duck. The little duck looked hungry, so Tom shared some sandwiches. Everyone smiled and had fun together. At the end of the day, Tom felt happy because sharing and helping friends is important.",
question:"What animal did Tom see?",
answers:["Duck","Lion","Elephant"],
correctAnswer:"Duck",
},
{
minAge:5,maxAge:7,
title:"The Friendly Rabbit",
text:"Mia had a happy day today. In the morning, Mia went to the playground with friends. They laughed, played games, and saw many interesting things. Near a tree, Mia saw a friendly rabbit. The little rabbit looked hungry, so Mia shared some cupcakes. Everyone smiled and had fun together. At the end of the day, Mia felt happy because sharing and helping friends is important.",
question:"What animal did Mia see?",
answers:["Rabbit","Lion","Elephant"],
correctAnswer:"Rabbit",
},
{
minAge:5,maxAge:7,
title:"Noah and the Magic Day",
text:"Noah had a happy day today. In the morning, Noah went to the school garden with friends. They laughed, played games, and saw many interesting things. Near a tree, Noah saw a friendly cat. The little cat looked hungry, so Noah shared some cookies. Everyone smiled and had fun together. At the end of the day, Noah felt happy because sharing and helping friends is important.",
question:"What animal did Noah see?",
answers:["Cat","Lion","Elephant"],
correctAnswer:"Cat",
},
{
minAge:5,maxAge:7,
title:"The Friendly Horse",
text:"Noah had a happy day today. In the morning, Noah went to the school garden with friends. They laughed, played games, and saw many interesting things. Near a tree, Noah saw a friendly horse. The little horse looked hungry, so Noah shared some bananas. Everyone smiled and had fun together. At the end of the day, Noah felt happy because sharing and helping friends is important.",
question:"What animal did Noah see?",
answers:["Horse","Lion","Elephant"],
correctAnswer:"Horse",
},
{
minAge:5,maxAge:7,
title:"Max and the Little Duck",
text:"Max had a happy day today. In the morning, Max went to the school garden with friends. They laughed, played games, and saw many interesting things. Near a tree, Max saw a friendly duck. The little duck looked hungry, so Max shared some apples. Everyone smiled and had fun together. At the end of the day, Max felt happy because sharing and helping friends is important.",
question:"What animal did Max see?",
answers:["Duck","Lion","Elephant"],
correctAnswer:"Duck",
},
{
minAge:5,maxAge:7,
title:"Mia's Happy Adventure",
text:"Mia had a happy day today. In the morning, Mia went to the park with friends. They laughed, played games, and saw many interesting things. Near a tree, Mia saw a friendly bird. The little bird looked hungry, so Mia shared some sandwiches. Everyone smiled and had fun together. At the end of the day, Mia felt happy because sharing and helping friends is important.",
question:"What animal did Mia see?",
answers:["Bird","Lion","Elephant"],
correctAnswer:"Bird",
},
{
minAge:5,maxAge:7,
title:"The Friendly Cat",
text:"Mila had a happy day today. In the morning, Mila went to the playground with friends. They laughed, played games, and saw many interesting things. Near a tree, Mila saw a friendly cat. The little cat looked hungry, so Mila shared some cupcakes. Everyone smiled and had fun together. At the end of the day, Mila felt happy because sharing and helping friends is important.",
question:"What animal did Mila see?",
answers:["Cat","Lion","Elephant"],
correctAnswer:"Cat",
},
{
minAge:5,maxAge:7,
title:"The Day at the Playground",
text:"Ben had a happy day today. In the morning, Ben went to the playground with friends. They laughed, played games, and saw many interesting things. Near a tree, Ben saw a friendly cat. The little cat looked hungry, so Ben shared some bananas. Everyone smiled and had fun together. At the end of the day, Ben felt happy because sharing and helping friends is important.",
question:"What animal did Ben see?",
answers:["Cat","Lion","Elephant"],
correctAnswer:"Cat",
},
{
minAge:5,maxAge:7,
title:"The Day at the Park",
text:"Mia had a happy day today. In the morning, Mia went to the park with friends. They laughed, played games, and saw many interesting things. Near a tree, Mia saw a friendly horse. The little horse looked hungry, so Mia shared some cupcakes. Everyone smiled and had fun together. At the end of the day, Mia felt happy because sharing and helping friends is important.",
question:"What animal did Mia see?",
answers:["Horse","Lion","Elephant"],
correctAnswer:"Horse",
},
{
minAge:5,maxAge:7,
title:"The Day at the Lake",
text:"Tom had a happy day today. In the morning, Tom went to the lake with friends. They laughed, played games, and saw many interesting things. Near a tree, Tom saw a friendly duck. The little duck looked hungry, so Tom shared some sandwiches. Everyone smiled and had fun together. At the end of the day, Tom felt happy because sharing and helping friends is important.",
question:"What animal did Tom see?",
answers:["Duck","Lion","Elephant"],
correctAnswer:"Duck",
},
{
minAge:5,maxAge:7,
title:"Sofia's Happy Adventure",
text:"Sofia had a happy day today. In the morning, Sofia went to the park with friends. They laughed, played games, and saw many interesting things. Near a tree, Sofia saw a friendly rabbit. The little rabbit looked hungry, so Sofia shared some carrots. Everyone smiled and had fun together. At the end of the day, Sofia felt happy because sharing and helping friends is important.",
question:"What animal did Sofia see?",
answers:["Rabbit","Lion","Elephant"],
correctAnswer:"Rabbit",
},
{
minAge:5,maxAge:7,
title:"Ben and the Magic Day",
text:"Ben had a happy day today. In the morning, Ben went to the playground with friends. They laughed, played games, and saw many interesting things. Near a tree, Ben saw a friendly rabbit. The little rabbit looked hungry, so Ben shared some carrots. Everyone smiled and had fun together. At the end of the day, Ben felt happy because sharing and helping friends is important.",
question:"What animal did Ben see?",
answers:["Rabbit","Lion","Elephant"],
correctAnswer:"Rabbit",
},
{
minAge:5,maxAge:7,
title:"The Day at the Farm",
text:"Sofia had a happy day today. In the morning, Sofia went to the farm with friends. They laughed, played games, and saw many interesting things. Near a tree, Sofia saw a friendly dog. The little dog looked hungry, so Sofia shared some apples. Everyone smiled and had fun together. At the end of the day, Sofia felt happy because sharing and helping friends is important.",
question:"What animal did Sofia see?",
answers:["Dog","Lion","Elephant"],
correctAnswer:"Dog",
},
{
minAge:5,maxAge:7,
title:"Sofia and the Magic Day",
text:"Sofia had a happy day today. In the morning, Sofia went to the zoo with friends. They laughed, played games, and saw many interesting things. Near a tree, Sofia saw a friendly dog. The little dog looked hungry, so Sofia shared some apples. Everyone smiled and had fun together. At the end of the day, Sofia felt happy because sharing and helping friends is important.",
question:"What animal did Sofia see?",
answers:["Dog","Lion","Elephant"],
correctAnswer:"Dog",
},
{
minAge:5,maxAge:7,
title:"Emma's Happy Adventure",
text:"Emma had a happy day today. In the morning, Emma went to the school garden with friends. They laughed, played games, and saw many interesting things. Near a tree, Emma saw a friendly horse. The little horse looked hungry, so Emma shared some bananas. Everyone smiled and had fun together. At the end of the day, Emma felt happy because sharing and helping friends is important.",
question:"What animal did Emma see?",
answers:["Horse","Lion","Elephant"],
correctAnswer:"Horse",
},
{
minAge:5,maxAge:7,
title:"Emma and the Little Horse",
text:"Emma had a happy day today. In the morning, Emma went to the school garden with friends. They laughed, played games, and saw many interesting things. Near a tree, Emma saw a friendly horse. The little horse looked hungry, so Emma shared some sandwiches. Everyone smiled and had fun together. At the end of the day, Emma felt happy because sharing and helping friends is important.",
question:"What animal did Emma see?",
answers:["Horse","Lion","Elephant"],
correctAnswer:"Horse",
},
{
minAge:5,maxAge:7,
title:"Sofia and the Little Horse",
text:"Sofia had a happy day today. In the morning, Sofia went to the lake with friends. They laughed, played games, and saw many interesting things. Near a tree, Sofia saw a friendly horse. The little horse looked hungry, so Sofia shared some cookies. Everyone smiled and had fun together. At the end of the day, Sofia felt happy because sharing and helping friends is important.",
question:"What animal did Sofia see?",
answers:["Horse","Lion","Elephant"],
correctAnswer:"Horse",
},
{
minAge:5,maxAge:7,
title:"Mia's Happy Adventure",
text:"Mia had a happy day today. In the morning, Mia went to the playground with friends. They laughed, played games, and saw many interesting things. Near a tree, Mia saw a friendly dog. The little dog looked hungry, so Mia shared some apples. Everyone smiled and had fun together. At the end of the day, Mia felt happy because sharing and helping friends is important.",
question:"What animal did Mia see?",
answers:["Dog","Lion","Elephant"],
correctAnswer:"Dog",
},
{
minAge:5,maxAge:7,
title:"Sofia and the Magic Day",
text:"Sofia had a happy day today. In the morning, Sofia went to the school garden with friends. They laughed, played games, and saw many interesting things. Near a tree, Sofia saw a friendly dog. The little dog looked hungry, so Sofia shared some carrots. Everyone smiled and had fun together. At the end of the day, Sofia felt happy because sharing and helping friends is important.",
question:"What animal did Sofia see?",
answers:["Dog","Lion","Elephant"],
correctAnswer:"Dog",
},
{
minAge:5,maxAge:7,
title:"Noah and the Magic Day",
text:"Noah had a happy day today. In the morning, Noah went to the farm with friends. They laughed, played games, and saw many interesting things. Near a tree, Noah saw a friendly cat. The little cat looked hungry, so Noah shared some cookies. Everyone smiled and had fun together. At the end of the day, Noah felt happy because sharing and helping friends is important.",
question:"What animal did Noah see?",
answers:["Cat","Lion","Elephant"],
correctAnswer:"Cat",
},
{
minAge:5,maxAge:7,
title:"Max and the Magic Day",
text:"Max had a happy day today. In the morning, Max went to the school garden with friends. They laughed, played games, and saw many interesting things. Near a tree, Max saw a friendly rabbit. The little rabbit looked hungry, so Max shared some sandwiches. Everyone smiled and had fun together. At the end of the day, Max felt happy because sharing and helping friends is important.",
question:"What animal did Max see?",
answers:["Rabbit","Lion","Elephant"],
correctAnswer:"Rabbit",
},
{
minAge:5,maxAge:7,
title:"Mia and the Little Rabbit",
text:"Mia had a happy day today. In the morning, Mia went to the school garden with friends. They laughed, played games, and saw many interesting things. Near a tree, Mia saw a friendly rabbit. The little rabbit looked hungry, so Mia shared some sandwiches. Everyone smiled and had fun together. At the end of the day, Mia felt happy because sharing and helping friends is important.",
question:"What animal did Mia see?",
answers:["Rabbit","Lion","Elephant"],
correctAnswer:"Rabbit",
},
{
minAge:5,maxAge:7,
title:"Sofia's Happy Adventure",
text:"Sofia had a happy day today. In the morning, Sofia went to the playground with friends. They laughed, played games, and saw many interesting things. Near a tree, Sofia saw a friendly bird. The little bird looked hungry, so Sofia shared some apples. Everyone smiled and had fun together. At the end of the day, Sofia felt happy because sharing and helping friends is important.",
question:"What animal did Sofia see?",
answers:["Bird","Lion","Elephant"],
correctAnswer:"Bird",
},
{
minAge:5,maxAge:7,
title:"Ben and the Magic Day",
text:"Ben had a happy day today. In the morning, Ben went to the lake with friends. They laughed, played games, and saw many interesting things. Near a tree, Ben saw a friendly bird. The little bird looked hungry, so Ben shared some apples. Everyone smiled and had fun together. At the end of the day, Ben felt happy because sharing and helping friends is important.",
question:"What animal did Ben see?",
answers:["Bird","Lion","Elephant"],
correctAnswer:"Bird",
},
{
minAge:5,maxAge:7,
title:"Emma and the Little Horse",
text:"Emma had a happy day today. In the morning, Emma went to the school garden with friends. They laughed, played games, and saw many interesting things. Near a tree, Emma saw a friendly horse. The little horse looked hungry, so Emma shared some bananas. Everyone smiled and had fun together. At the end of the day, Emma felt happy because sharing and helping friends is important.",
question:"What animal did Emma see?",
answers:["Horse","Lion","Elephant"],
correctAnswer:"Horse",
},
{
minAge:5,maxAge:7,
title:"The Friendly Horse",
text:"Noah had a happy day today. In the morning, Noah went to the zoo with friends. They laughed, played games, and saw many interesting things. Near a tree, Noah saw a friendly horse. The little horse looked hungry, so Noah shared some apples. Everyone smiled and had fun together. At the end of the day, Noah felt happy because sharing and helping friends is important.",
question:"What animal did Noah see?",
answers:["Horse","Lion","Elephant"],
correctAnswer:"Horse",
},
]
};