export const readingTexts={
leicht:[
{
minAge:6,
maxAge:8,
title:"Der bunte Zug 1",
text:"Ben, Mila und Noah spielten zusammen an einem schönen Ort. Ben trug ein rotes T-Shirt, Mila ein blaues T-Shirt und Noah ein grünes T-Shirt. Mila stand nicht neben Noah. Ben stand links von Mila. Die Kinder lachten und hatten viel Spaß zusammen.",
question:"Wer stand in der Mitte?",
answers:["Ben","Mila","Noah"],
correctAnswer:"Mila",
},
{
minAge:6,
maxAge:8,
title:"Das Tierrennen 2",
text:"Ben, Mila und Noah spielten zusammen an einem schönen Ort. Ben trug ein rotes T-Shirt, Mila ein blaues T-Shirt und Noah ein grünes T-Shirt. Mila stand nicht neben Noah. Ben stand links von Mila. Die Kinder lachten und hatten viel Spaß zusammen.",
question:"Wer stand in der Mitte?",
answers:["Ben","Mila","Noah"],
correctAnswer:"Mila",
},
{
minAge:6,
maxAge:8,
title:"Die drei Freunde 3",
text:"Ben, Mila und Noah spielten zusammen an einem schönen Ort. Ben trug ein rotes T-Shirt, Mila ein blaues T-Shirt und Noah ein grünes T-Shirt. Mila stand nicht neben Noah. Ben stand links von Mila. Die Kinder lachten und hatten viel Spaß zusammen.",
question:"Wer stand in der Mitte?",
answers:["Ben","Mila","Noah"],
correctAnswer:"Mila",
},
{
minAge:6,
maxAge:8,
title:"Der Zauberwald 4",
text:"Ben, Mila und Noah spielten zusammen an einem schönen Ort. Ben trug ein rotes T-Shirt, Mila ein blaues T-Shirt und Noah ein grünes T-Shirt. Mila stand nicht neben Noah. Ben stand links von Mila. Die Kinder lachten und hatten viel Spaß zusammen.",
question:"Wer stand in der Mitte?",
answers:["Ben","Mila","Noah"],
correctAnswer:"Mila",
},
{
minAge:6,
maxAge:8,
title:"Der Bauernhof 5",
text:"Ben, Mila und Noah spielten zusammen an einem schönen Ort. Ben trug ein rotes T-Shirt, Mila ein blaues T-Shirt und Noah ein grünes T-Shirt. Mila stand nicht neben Noah. Ben stand links von Mila. Die Kinder lachten und hatten viel Spaß zusammen.",
question:"Wer stand in der Mitte?",
answers:["Ben","Mila","Noah"],
correctAnswer:"Mila",
},
{
minAge:6,
maxAge:8,
title:"Die Schatzsuche 6",
text:"Ben, Mila und Noah spielten zusammen an einem schönen Ort. Ben trug ein rotes T-Shirt, Mila ein blaues T-Shirt und Noah ein grünes T-Shirt. Mila stand nicht neben Noah. Ben stand links von Mila. Die Kinder lachten und hatten viel Spaß zusammen.",
question:"Wer stand in der Mitte?",
answers:["Ben","Mila","Noah"],
correctAnswer:"Mila",
},
{
minAge:6,
maxAge:8,
title:"Das Picknick 7",
text:"Ben, Mila und Noah spielten zusammen an einem schönen Ort. Ben trug ein rotes T-Shirt, Mila ein blaues T-Shirt und Noah ein grünes T-Shirt. Mila stand nicht neben Noah. Ben stand links von Mila. Die Kinder lachten und hatten viel Spaß zusammen.",
question:"Wer stand in der Mitte?",
answers:["Ben","Mila","Noah"],
correctAnswer:"Mila",
},
{
minAge:6,
maxAge:8,
title:"Die Wolkenreise 8",
text:"Ben, Mila und Noah spielten zusammen an einem schönen Ort. Ben trug ein rotes T-Shirt, Mila ein blaues T-Shirt und Noah ein grünes T-Shirt. Mila stand nicht neben Noah. Ben stand links von Mila. Die Kinder lachten und hatten viel Spaß zusammen.",
question:"Wer stand in der Mitte?",
answers:["Ben","Mila","Noah"],
correctAnswer:"Mila",
},
{
minAge:6,
maxAge:8,
title:"Der Spielplatz 9",
text:"Ben, Mila und Noah spielten zusammen an einem schönen Ort. Ben trug ein rotes T-Shirt, Mila ein blaues T-Shirt und Noah ein grünes T-Shirt. Mila stand nicht neben Noah. Ben stand links von Mila. Die Kinder lachten und hatten viel Spaß zusammen.",
question:"Wer stand in der Mitte?",
answers:["Ben","Mila","Noah"],
correctAnswer:"Mila",
},
{
minAge:6,
maxAge:8,
title:"Der Tierpark 10",
text:"Ben, Mila und Noah spielten zusammen an einem schönen Ort. Ben trug ein rotes T-Shirt, Mila ein blaues T-Shirt und Noah ein grünes T-Shirt. Mila stand nicht neben Noah. Ben stand links von Mila. Die Kinder lachten und hatten viel Spaß zusammen.",
question:"Wer stand in der Mitte?",
answers:["Ben","Mila","Noah"],
correctAnswer:"Mila",
},
{
minAge:6,
maxAge:8,
title:"Der bunte Zug 11",
text:"Ben, Mila und Noah spielten zusammen an einem schönen Ort. Ben trug ein rotes T-Shirt, Mila ein blaues T-Shirt und Noah ein grünes T-Shirt. Mila stand nicht neben Noah. Ben stand links von Mila. Die Kinder lachten und hatten viel Spaß zusammen.",
question:"Wer stand in der Mitte?",
answers:["Ben","Mila","Noah"],
correctAnswer:"Mila",
},
{
minAge:6,
maxAge:8,
title:"Das Tierrennen 12",
text:"Ben, Mila und Noah spielten zusammen an einem schönen Ort. Ben trug ein rotes T-Shirt, Mila ein blaues T-Shirt und Noah ein grünes T-Shirt. Mila stand nicht neben Noah. Ben stand links von Mila. Die Kinder lachten und hatten viel Spaß zusammen.",
question:"Wer stand in der Mitte?",
answers:["Ben","Mila","Noah"],
correctAnswer:"Mila",
},
{
minAge:6,
maxAge:8,
title:"Die drei Freunde 13",
text:"Ben, Mila und Noah spielten zusammen an einem schönen Ort. Ben trug ein rotes T-Shirt, Mila ein blaues T-Shirt und Noah ein grünes T-Shirt. Mila stand nicht neben Noah. Ben stand links von Mila. Die Kinder lachten und hatten viel Spaß zusammen.",
question:"Wer stand in der Mitte?",
answers:["Ben","Mila","Noah"],
correctAnswer:"Mila",
},
{
minAge:6,
maxAge:8,
title:"Der Zauberwald 14",
text:"Ben, Mila und Noah spielten zusammen an einem schönen Ort. Ben trug ein rotes T-Shirt, Mila ein blaues T-Shirt und Noah ein grünes T-Shirt. Mila stand nicht neben Noah. Ben stand links von Mila. Die Kinder lachten und hatten viel Spaß zusammen.",
question:"Wer stand in der Mitte?",
answers:["Ben","Mila","Noah"],
correctAnswer:"Mila",
},
{
minAge:6,
maxAge:8,
title:"Der Bauernhof 15",
text:"Ben, Mila und Noah spielten zusammen an einem schönen Ort. Ben trug ein rotes T-Shirt, Mila ein blaues T-Shirt und Noah ein grünes T-Shirt. Mila stand nicht neben Noah. Ben stand links von Mila. Die Kinder lachten und hatten viel Spaß zusammen.",
question:"Wer stand in der Mitte?",
answers:["Ben","Mila","Noah"],
correctAnswer:"Mila",
},
{
minAge:6,
maxAge:8,
title:"Die Schatzsuche 16",
text:"Ben, Mila und Noah spielten zusammen an einem schönen Ort. Ben trug ein rotes T-Shirt, Mila ein blaues T-Shirt und Noah ein grünes T-Shirt. Mila stand nicht neben Noah. Ben stand links von Mila. Die Kinder lachten und hatten viel Spaß zusammen.",
question:"Wer stand in der Mitte?",
answers:["Ben","Mila","Noah"],
correctAnswer:"Mila",
},
{
minAge:6,
maxAge:8,
title:"Das Picknick 17",
text:"Ben, Mila und Noah spielten zusammen an einem schönen Ort. Ben trug ein rotes T-Shirt, Mila ein blaues T-Shirt und Noah ein grünes T-Shirt. Mila stand nicht neben Noah. Ben stand links von Mila. Die Kinder lachten und hatten viel Spaß zusammen.",
question:"Wer stand in der Mitte?",
answers:["Ben","Mila","Noah"],
correctAnswer:"Mila",
},
{
minAge:6,
maxAge:8,
title:"Die Wolkenreise 18",
text:"Ben, Mila und Noah spielten zusammen an einem schönen Ort. Ben trug ein rotes T-Shirt, Mila ein blaues T-Shirt und Noah ein grünes T-Shirt. Mila stand nicht neben Noah. Ben stand links von Mila. Die Kinder lachten und hatten viel Spaß zusammen.",
question:"Wer stand in der Mitte?",
answers:["Ben","Mila","Noah"],
correctAnswer:"Mila",
},
{
minAge:6,
maxAge:8,
title:"Der Spielplatz 19",
text:"Ben, Mila und Noah spielten zusammen an einem schönen Ort. Ben trug ein rotes T-Shirt, Mila ein blaues T-Shirt und Noah ein grünes T-Shirt. Mila stand nicht neben Noah. Ben stand links von Mila. Die Kinder lachten und hatten viel Spaß zusammen.",
question:"Wer stand in der Mitte?",
answers:["Ben","Mila","Noah"],
correctAnswer:"Mila",
},
{
minAge:6,
maxAge:8,
title:"Der Tierpark 20",
text:"Ben, Mila und Noah spielten zusammen an einem schönen Ort. Ben trug ein rotes T-Shirt, Mila ein blaues T-Shirt und Noah ein grünes T-Shirt. Mila stand nicht neben Noah. Ben stand links von Mila. Die Kinder lachten und hatten viel Spaß zusammen.",
question:"Wer stand in der Mitte?",
answers:["Ben","Mila","Noah"],
correctAnswer:"Mila",
},
{
minAge:6,
maxAge:8,
title:"Der bunte Zug 21",
text:"Ben, Mila und Noah spielten zusammen an einem schönen Ort. Ben trug ein rotes T-Shirt, Mila ein blaues T-Shirt und Noah ein grünes T-Shirt. Mila stand nicht neben Noah. Ben stand links von Mila. Die Kinder lachten und hatten viel Spaß zusammen.",
question:"Wer stand in der Mitte?",
answers:["Ben","Mila","Noah"],
correctAnswer:"Mila",
},
{
minAge:6,
maxAge:8,
title:"Das Tierrennen 22",
text:"Ben, Mila und Noah spielten zusammen an einem schönen Ort. Ben trug ein rotes T-Shirt, Mila ein blaues T-Shirt und Noah ein grünes T-Shirt. Mila stand nicht neben Noah. Ben stand links von Mila. Die Kinder lachten und hatten viel Spaß zusammen.",
question:"Wer stand in der Mitte?",
answers:["Ben","Mila","Noah"],
correctAnswer:"Mila",
},
{
minAge:6,
maxAge:8,
title:"Die drei Freunde 23",
text:"Ben, Mila und Noah spielten zusammen an einem schönen Ort. Ben trug ein rotes T-Shirt, Mila ein blaues T-Shirt und Noah ein grünes T-Shirt. Mila stand nicht neben Noah. Ben stand links von Mila. Die Kinder lachten und hatten viel Spaß zusammen.",
question:"Wer stand in der Mitte?",
answers:["Ben","Mila","Noah"],
correctAnswer:"Mila",
},
{
minAge:6,
maxAge:8,
title:"Der Zauberwald 24",
text:"Ben, Mila und Noah spielten zusammen an einem schönen Ort. Ben trug ein rotes T-Shirt, Mila ein blaues T-Shirt und Noah ein grünes T-Shirt. Mila stand nicht neben Noah. Ben stand links von Mila. Die Kinder lachten und hatten viel Spaß zusammen.",
question:"Wer stand in der Mitte?",
answers:["Ben","Mila","Noah"],
correctAnswer:"Mila",
},
{
minAge:6,
maxAge:8,
title:"Der Bauernhof 25",
text:"Ben, Mila und Noah spielten zusammen an einem schönen Ort. Ben trug ein rotes T-Shirt, Mila ein blaues T-Shirt und Noah ein grünes T-Shirt. Mila stand nicht neben Noah. Ben stand links von Mila. Die Kinder lachten und hatten viel Spaß zusammen.",
question:"Wer stand in der Mitte?",
answers:["Ben","Mila","Noah"],
correctAnswer:"Mila",
},
{
minAge:6,
maxAge:8,
title:"Die Schatzsuche 26",
text:"Ben, Mila und Noah spielten zusammen an einem schönen Ort. Ben trug ein rotes T-Shirt, Mila ein blaues T-Shirt und Noah ein grünes T-Shirt. Mila stand nicht neben Noah. Ben stand links von Mila. Die Kinder lachten und hatten viel Spaß zusammen.",
question:"Wer stand in der Mitte?",
answers:["Ben","Mila","Noah"],
correctAnswer:"Mila",
},
{
minAge:6,
maxAge:8,
title:"Das Picknick 27",
text:"Ben, Mila und Noah spielten zusammen an einem schönen Ort. Ben trug ein rotes T-Shirt, Mila ein blaues T-Shirt und Noah ein grünes T-Shirt. Mila stand nicht neben Noah. Ben stand links von Mila. Die Kinder lachten und hatten viel Spaß zusammen.",
question:"Wer stand in der Mitte?",
answers:["Ben","Mila","Noah"],
correctAnswer:"Mila",
},
{
minAge:6,
maxAge:8,
title:"Die Wolkenreise 28",
text:"Ben, Mila und Noah spielten zusammen an einem schönen Ort. Ben trug ein rotes T-Shirt, Mila ein blaues T-Shirt und Noah ein grünes T-Shirt. Mila stand nicht neben Noah. Ben stand links von Mila. Die Kinder lachten und hatten viel Spaß zusammen.",
question:"Wer stand in der Mitte?",
answers:["Ben","Mila","Noah"],
correctAnswer:"Mila",
},
{
minAge:6,
maxAge:8,
title:"Der Spielplatz 29",
text:"Ben, Mila und Noah spielten zusammen an einem schönen Ort. Ben trug ein rotes T-Shirt, Mila ein blaues T-Shirt und Noah ein grünes T-Shirt. Mila stand nicht neben Noah. Ben stand links von Mila. Die Kinder lachten und hatten viel Spaß zusammen.",
question:"Wer stand in der Mitte?",
answers:["Ben","Mila","Noah"],
correctAnswer:"Mila",
},
{
minAge:6,
maxAge:8,
title:"Der Tierpark 30",
text:"Ben, Mila und Noah spielten zusammen an einem schönen Ort. Ben trug ein rotes T-Shirt, Mila ein blaues T-Shirt und Noah ein grünes T-Shirt. Mila stand nicht neben Noah. Ben stand links von Mila. Die Kinder lachten und hatten viel Spaß zusammen.",
question:"Wer stand in der Mitte?",
answers:["Ben","Mila","Noah"],
correctAnswer:"Mila",
},
{
minAge:6,
maxAge:8,
title:"Der bunte Zug 31",
text:"Ben, Mila und Noah spielten zusammen an einem schönen Ort. Ben trug ein rotes T-Shirt, Mila ein blaues T-Shirt und Noah ein grünes T-Shirt. Mila stand nicht neben Noah. Ben stand links von Mila. Die Kinder lachten und hatten viel Spaß zusammen.",
question:"Wer stand in der Mitte?",
answers:["Ben","Mila","Noah"],
correctAnswer:"Mila",
},
{
minAge:6,
maxAge:8,
title:"Das Tierrennen 32",
text:"Ben, Mila und Noah spielten zusammen an einem schönen Ort. Ben trug ein rotes T-Shirt, Mila ein blaues T-Shirt und Noah ein grünes T-Shirt. Mila stand nicht neben Noah. Ben stand links von Mila. Die Kinder lachten und hatten viel Spaß zusammen.",
question:"Wer stand in der Mitte?",
answers:["Ben","Mila","Noah"],
correctAnswer:"Mila",
},
{
minAge:6,
maxAge:8,
title:"Die drei Freunde 33",
text:"Ben, Mila und Noah spielten zusammen an einem schönen Ort. Ben trug ein rotes T-Shirt, Mila ein blaues T-Shirt und Noah ein grünes T-Shirt. Mila stand nicht neben Noah. Ben stand links von Mila. Die Kinder lachten und hatten viel Spaß zusammen.",
question:"Wer stand in der Mitte?",
answers:["Ben","Mila","Noah"],
correctAnswer:"Mila",
},
{
minAge:6,
maxAge:8,
title:"Der Zauberwald 34",
text:"Ben, Mila und Noah spielten zusammen an einem schönen Ort. Ben trug ein rotes T-Shirt, Mila ein blaues T-Shirt und Noah ein grünes T-Shirt. Mila stand nicht neben Noah. Ben stand links von Mila. Die Kinder lachten und hatten viel Spaß zusammen.",
question:"Wer stand in der Mitte?",
answers:["Ben","Mila","Noah"],
correctAnswer:"Mila",
},
{
minAge:6,
maxAge:8,
title:"Der Bauernhof 35",
text:"Ben, Mila und Noah spielten zusammen an einem schönen Ort. Ben trug ein rotes T-Shirt, Mila ein blaues T-Shirt und Noah ein grünes T-Shirt. Mila stand nicht neben Noah. Ben stand links von Mila. Die Kinder lachten und hatten viel Spaß zusammen.",
question:"Wer stand in der Mitte?",
answers:["Ben","Mila","Noah"],
correctAnswer:"Mila",
},
{
minAge:6,
maxAge:8,
title:"Die Schatzsuche 36",
text:"Ben, Mila und Noah spielten zusammen an einem schönen Ort. Ben trug ein rotes T-Shirt, Mila ein blaues T-Shirt und Noah ein grünes T-Shirt. Mila stand nicht neben Noah. Ben stand links von Mila. Die Kinder lachten und hatten viel Spaß zusammen.",
question:"Wer stand in der Mitte?",
answers:["Ben","Mila","Noah"],
correctAnswer:"Mila",
},
{
minAge:6,
maxAge:8,
title:"Das Picknick 37",
text:"Ben, Mila und Noah spielten zusammen an einem schönen Ort. Ben trug ein rotes T-Shirt, Mila ein blaues T-Shirt und Noah ein grünes T-Shirt. Mila stand nicht neben Noah. Ben stand links von Mila. Die Kinder lachten und hatten viel Spaß zusammen.",
question:"Wer stand in der Mitte?",
answers:["Ben","Mila","Noah"],
correctAnswer:"Mila",
},
{
minAge:6,
maxAge:8,
title:"Die Wolkenreise 38",
text:"Ben, Mila und Noah spielten zusammen an einem schönen Ort. Ben trug ein rotes T-Shirt, Mila ein blaues T-Shirt und Noah ein grünes T-Shirt. Mila stand nicht neben Noah. Ben stand links von Mila. Die Kinder lachten und hatten viel Spaß zusammen.",
question:"Wer stand in der Mitte?",
answers:["Ben","Mila","Noah"],
correctAnswer:"Mila",
},
{
minAge:6,
maxAge:8,
title:"Der Spielplatz 39",
text:"Ben, Mila und Noah spielten zusammen an einem schönen Ort. Ben trug ein rotes T-Shirt, Mila ein blaues T-Shirt und Noah ein grünes T-Shirt. Mila stand nicht neben Noah. Ben stand links von Mila. Die Kinder lachten und hatten viel Spaß zusammen.",
question:"Wer stand in der Mitte?",
answers:["Ben","Mila","Noah"],
correctAnswer:"Mila",
},
{
minAge:6,
maxAge:8,
title:"Der Tierpark 40",
text:"Ben, Mila und Noah spielten zusammen an einem schönen Ort. Ben trug ein rotes T-Shirt, Mila ein blaues T-Shirt und Noah ein grünes T-Shirt. Mila stand nicht neben Noah. Ben stand links von Mila. Die Kinder lachten und hatten viel Spaß zusammen.",
question:"Wer stand in der Mitte?",
answers:["Ben","Mila","Noah"],
correctAnswer:"Mila",
},
{
minAge:6,
maxAge:8,
title:"Der bunte Zug 41",
text:"Ben, Mila und Noah spielten zusammen an einem schönen Ort. Ben trug ein rotes T-Shirt, Mila ein blaues T-Shirt und Noah ein grünes T-Shirt. Mila stand nicht neben Noah. Ben stand links von Mila. Die Kinder lachten und hatten viel Spaß zusammen.",
question:"Wer stand in der Mitte?",
answers:["Ben","Mila","Noah"],
correctAnswer:"Mila",
},
{
minAge:6,
maxAge:8,
title:"Das Tierrennen 42",
text:"Ben, Mila und Noah spielten zusammen an einem schönen Ort. Ben trug ein rotes T-Shirt, Mila ein blaues T-Shirt und Noah ein grünes T-Shirt. Mila stand nicht neben Noah. Ben stand links von Mila. Die Kinder lachten und hatten viel Spaß zusammen.",
question:"Wer stand in der Mitte?",
answers:["Ben","Mila","Noah"],
correctAnswer:"Mila",
},
{
minAge:6,
maxAge:8,
title:"Die drei Freunde 43",
text:"Ben, Mila und Noah spielten zusammen an einem schönen Ort. Ben trug ein rotes T-Shirt, Mila ein blaues T-Shirt und Noah ein grünes T-Shirt. Mila stand nicht neben Noah. Ben stand links von Mila. Die Kinder lachten und hatten viel Spaß zusammen.",
question:"Wer stand in der Mitte?",
answers:["Ben","Mila","Noah"],
correctAnswer:"Mila",
},
{
minAge:6,
maxAge:8,
title:"Der Zauberwald 44",
text:"Ben, Mila und Noah spielten zusammen an einem schönen Ort. Ben trug ein rotes T-Shirt, Mila ein blaues T-Shirt und Noah ein grünes T-Shirt. Mila stand nicht neben Noah. Ben stand links von Mila. Die Kinder lachten und hatten viel Spaß zusammen.",
question:"Wer stand in der Mitte?",
answers:["Ben","Mila","Noah"],
correctAnswer:"Mila",
},
{
minAge:6,
maxAge:8,
title:"Der Bauernhof 45",
text:"Ben, Mila und Noah spielten zusammen an einem schönen Ort. Ben trug ein rotes T-Shirt, Mila ein blaues T-Shirt und Noah ein grünes T-Shirt. Mila stand nicht neben Noah. Ben stand links von Mila. Die Kinder lachten und hatten viel Spaß zusammen.",
question:"Wer stand in der Mitte?",
answers:["Ben","Mila","Noah"],
correctAnswer:"Mila",
},
{
minAge:6,
maxAge:8,
title:"Die Schatzsuche 46",
text:"Ben, Mila und Noah spielten zusammen an einem schönen Ort. Ben trug ein rotes T-Shirt, Mila ein blaues T-Shirt und Noah ein grünes T-Shirt. Mila stand nicht neben Noah. Ben stand links von Mila. Die Kinder lachten und hatten viel Spaß zusammen.",
question:"Wer stand in der Mitte?",
answers:["Ben","Mila","Noah"],
correctAnswer:"Mila",
},
{
minAge:6,
maxAge:8,
title:"Das Picknick 47",
text:"Ben, Mila und Noah spielten zusammen an einem schönen Ort. Ben trug ein rotes T-Shirt, Mila ein blaues T-Shirt und Noah ein grünes T-Shirt. Mila stand nicht neben Noah. Ben stand links von Mila. Die Kinder lachten und hatten viel Spaß zusammen.",
question:"Wer stand in der Mitte?",
answers:["Ben","Mila","Noah"],
correctAnswer:"Mila",
},
{
minAge:6,
maxAge:8,
title:"Die Wolkenreise 48",
text:"Ben, Mila und Noah spielten zusammen an einem schönen Ort. Ben trug ein rotes T-Shirt, Mila ein blaues T-Shirt und Noah ein grünes T-Shirt. Mila stand nicht neben Noah. Ben stand links von Mila. Die Kinder lachten und hatten viel Spaß zusammen.",
question:"Wer stand in der Mitte?",
answers:["Ben","Mila","Noah"],
correctAnswer:"Mila",
},
{
minAge:6,
maxAge:8,
title:"Der Spielplatz 49",
text:"Ben, Mila und Noah spielten zusammen an einem schönen Ort. Ben trug ein rotes T-Shirt, Mila ein blaues T-Shirt und Noah ein grünes T-Shirt. Mila stand nicht neben Noah. Ben stand links von Mila. Die Kinder lachten und hatten viel Spaß zusammen.",
question:"Wer stand in der Mitte?",
answers:["Ben","Mila","Noah"],
correctAnswer:"Mila",
},
{
minAge:6,
maxAge:8,
title:"Der Tierpark 50",
text:"Ben, Mila und Noah spielten zusammen an einem schönen Ort. Ben trug ein rotes T-Shirt, Mila ein blaues T-Shirt und Noah ein grünes T-Shirt. Mila stand nicht neben Noah. Ben stand links von Mila. Die Kinder lachten und hatten viel Spaß zusammen.",
question:"Wer stand in der Mitte?",
answers:["Ben","Mila","Noah"],
correctAnswer:"Mila",
},
]
};